# Generated by Django 5.0 on 2023-12-11 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', 'initialData'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradata',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
