# Generated by Django 5.0 on 2023-12-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', 'initialData'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
