# Generated by Django 5.0 on 2023-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_extradata_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueTime',
            new_name='startTime',
        ),
        migrations.AddField(
            model_name='task',
            name='endTime',
            field=models.TimeField(blank=True, default='00:00'),
        ),
    ]
