# Generated by Django 5.0 on 2023-12-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_category_user_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
