# Generated by Django 5.0 on 2023-12-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_category_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user_id',
        ),
    ]
