# Generated by Django 5.0 on 2023-12-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradata',
            name='archive',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
