# Generated by Django 5.0 on 2023-12-11 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_duetime_task_starttime_task_endtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='startTime',
            new_name='dueTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='endTime',
        ),
    ]
