# Generated by Django 5.0 on 2023-12-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='taskDescription',
        ),
    ]
