# Generated by Django 5.0 on 2023-12-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_extradata_archive'),
        ('Task', '0003_rename_description_task_taskdescription'),
    ]

    operations = [
    ]
