# Generated by Django 5.0 on 2023-12-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_extradata_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='archive',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
